apiVersion: v1
kind: Secret

metadata:
  name: ecociente-mobile-env
  namespace: ecociente

type: Opaque

stringData:
  .env: |
    FACEBOOK_APP_ID=SEU_FACEBOOK_APP_ID
    FACEBOOK_CLIENT_TOKEN=SEU_FACEBOOK_CLIENT_TOKEN